[program:laravel-horizon]
process_name=%(program_name)s
command=php /var/www/laravel-radius/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/laravel-radius/storage/logs/horizon.log
stopwaitsecs=3600
